apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-ingress1
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: chart.example.com
    http:
      paths:
      - path: /num/(.*)$
        pathType: Prefix
        backend:
          service:
            name: new-service1
            port:
              number: 80

